# Environment parameters

env: InvertedDoublePendulum-v2
state_dim: 11
action_dim: 1
action_low: -1
action_high: 1
num_agents: 2
random_seed: 2019

# Training parameters

model: ddpg
batch_size: 256
num_steps_train: 100_000 # number of episodes from all agents
max_ep_length: 1000 # maximum number of steps per episode
replay_mem_size: 1_000_000 # maximum capacity of replay memory
discount_rate: 0.99 # Discount rate (gamma) for future rewards
n_step_returns: 5 # number of future steps to collect experiences for N-step returns
update_agent_ep: 1 # agent gets latest parameters from learner every update_agent_ep episodes
replay_queue_size: 64 # queue with replays from all the agents
batch_queue_size: 64 # queue with batches given to learner
num_episode_save: 100
device: cuda
agent_device: cpu
save_reward_threshold: 1 # difference in best reward to save agent model

# Network parameters

critic_learning_rate: 0.0005
actor_learning_rate: 0.0005
dense_size: 400 # size of the 2 hidden layers in networks
final_layer_init: 0.003
tau: 0.001 # parameter for soft target network updates

# Miscellaneous

results_path: results

